# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               jstanier
tagline:             'Here be dragons.'
description:         'A big splat of James Stanier on the Internet.'
url:                 http://jstanier.com
baseurl:             ''
paginate:            5
gems: ["jekyll-paginate"]

# About/contact
author:
  name:              James Stanier
  url:               https://twitter.com/jstanier
  email:             jamiestanier@gmail.com

# Custom vars
version:             1.0.0
